name: Build and push

on:
  workflow_dispatch:
    inputs:
      lokiDriverVersion:
        description: 'Loki Docker driver release version'     
        required: true
        default: '3.1.1'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/arm64

    - name: Build the Docker plugin
      run: sh build.sh ${{ github.event.inputs.lokiDriverVersion }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the Docker plugin to DockerHub
      run: sh push.sh ${{ github.event.inputs.lokiDriverVersion }}
